In [ ]:
Write a function to compute 5/0 and use try/except to catch the exceptions

In [23]:
def divbyzero(a,b):
    try:
        a/b
    except Exception as e :
            print(e)

In [24]:
divbyzero(5,0)

division by zero


In [ ]:
Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
Hint: Subject,Verb and Object should be declared in the program as shown below.
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

In [25]:
subjects=["Americans","Indians"]
verbs=["play","watch"] 
objects=["Baseball","Cricket"]

for s in subjects:
  for v in verbs:
    for o in objects:
      print(s+" "+v+" "+o+ ".")

Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


In [ ]:
Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

In [5]:
import numpy as np

def genmatrix(element,column):
    return np.column_stack([element**(column-1-i) for i in range(column)])

print(genmatrix(np.array([1, 2, 3, 4,5]),4))


def genmatrix(element,column):
    return np.vander(element,column)

print("\n Using Vendor Method : \n")
print(genmatrix(np.array([1, 2, 3, 4,5]),4))

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]]

 Using Vendor Method : 

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]]
